basket/urls.py
from django.urls import path

from basket.views import add_to_cart, cart_detail, remove_from_cart, delete_item

app_name = 'cart'
urlpatterns = [
    path('cart_detail/',cart_detail,name='cart_detail'),
    path('add_to_cart/<int:product_id>/',add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/',remove_from_cart,name='remove_from_cart'),
    path('delete_item/<int:product_id>/',delete_item,name='delete_item')
]

onlinestore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from products.urls import urlpatterns as product_urls
from basket.urls import urlpatterns as cart_patterns
from orders.urls import urlpatterns as order_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls',namespace='products')),
    path('cart/',include('basket.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('users/',include('users.urls',namespace='users'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import create_order, order_detail, orders_list

app_name = 'orders'
urlpatterns = [
    path('create_order/',create_order,name='create_order'),
    path('order_detail/<int:order_id>',order_detail,name='order_detail'),
    path('order_list/',orders_list,name='order_list')
]

products/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from products.views import product_detail, product_list

app_name = 'products'
urlpatterns = [
    path('', product_list, name='product_list'),
    path('products/<int:pk>/', product_detail, name='product_detail')

]

users/urls.py
from django.urls import path

from users.views import home, register, login_user,logout_user

app_name = 'users'
urlpatterns = [
    path('',home,name='home'),
    path('login/',login_user,name='login'),
    path('logout/',logout_user,name='logout'),
    path('registration/',register,name = 'register')
]

basket/models.py
from decimal import Decimal
from django.db import models

from products.models import Product
from users.models import User



class CartQueryset(models.QuerySet):
    def total_price(self):
        return sum([cart.products_price() for cart in self])
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class CartAndUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        db_table = 'cart_and_user'
        verbose_name = 'CartAndUser'
        verbose_name_plural = 'CartsAndeUsers'

class CartAndProduct(models.Model):
    cart = models.ForeignKey(CartAndUser,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    class Meta:
        db_table='cart_and_product'
        verbose_name='CartAndProduct'
        verbose_name_plural = 'CartsAndProducts'


    def products_price(self):
        return round(self.quantity*self.product.price)

basket/forms.py
from django import forms

from products.models import Product

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]
class CartForm(forms.Form):

	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
	update = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

basket/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404

from basket.models import CartAndUser, CartAndProduct
from basket.forms import CartForm

from products.models import Product
from django.views.decorators.http import require_POST




def add_to_cart(request,product_id):
    """Добавление товара в корзину"""
    if not request.user.is_authenticated:
        return redirect('users:login')
    product = Product.objects.get(pk=product_id)
    carts_users = CartAndUser.objects.filter(user_id=request.user.id).last()

    #Если нет корзины, то создаем ее
    if not carts_users:
        carts_users=CartAndUser.objects.create(user_id=request.user.id)

    #Если нет товаров в корзине, то добавляем товар
    carts_products = CartAndProduct.objects.filter(cart_id=carts_users.pk, product_id=product.id)
    if not carts_products:
        CartAndProduct.objects.create(cart_id=carts_users.pk,product_id=product.id,quantity=0)

    #Если есть товар в корзине, то увеличиваем количество
    quantity = carts_products.last().quantity


    quantity+=1
    #Если количество товара в корзине превышает количество на складе, то выводим сообщение с ошибкой
    if quantity>product.quantity:
        messages.error(request, f'Количество товара <{product.name}> ограничено (максимум {product.quantity})')
        return redirect('cart:cart_detail')
    carts_products.update(quantity=quantity)
    return redirect('cart:cart_detail')


def remove_from_cart(request,product_id):
    """Удаление товара из корзины"""
    if not request.user.is_authenticated:
        return redirect('users:login')
    product = Product.objects.get(pk=product_id)
    if not request.user.is_authenticated:
        return redirect('users:login')
    cart = CartAndUser.objects.filter(user_id=request.user.id).last()
    CartAndProduct.objects.filter(cart_id=cart.pk,product=product.id).delete()
    return redirect('cart:cart_detail')

def delete_item(request,product_id):
    """Уменьшение количества товара в корзине"""
    if not request.user.is_authenticated:
        return redirect('users:login')
    product = Product.objects.get(pk=product_id)
    cart = CartAndUser.objects.filter(user_id=request.user.id).last()
    cart = CartAndProduct.objects.filter(cart_id=cart.pk,product_id=product.id)
    if cart:
        quantity = cart.last().quantity
        quantity -=1
        cart.update(quantity=quantity)
        #Если в корзине количество товара 0, то удаляем его из корзины
        if cart.last().quantity==0:
            remove_from_cart(request,product_id)
    return redirect('cart:cart_detail')
def cart_detail(request):
    """Информация о корзине"""
    if not request.user.is_authenticated:
        return redirect('users:login')
    cart_user = CartAndUser.objects.filter(user=request.user.id).last()
    if not cart_user:
        CartAndUser.objects.create(user_id=request.user.id)
        cart_user = CartAndUser.objects.filter(user=request.user.id).last()
    cart = CartAndProduct.objects.filter(cart=cart_user.id).order_by('product_id')
    price = sum(item.products_price() for item in cart )

    return render(request,'basket/cart.html',{'cart':cart,'price':price})

templates/basket/cart.html
{% extends "products/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cart</title>
</head>
<body>
{% block content%}
<div style="margin-left:30px; margin-bottom:30px;" class="">
    <h1>Your shopping cart</h1>
    {% if messages%}
        <ul class="messages">

    {% for message in messages %}

        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>

            {{ message }}

        </li>

    {% endfor %}

    </ul>

    {% endif %}
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th>Товар</th>
            <th>Стоимость товара</th>
            <th>Удалить товар</th>
            <th>Количество</th>
            <th> - </th>
            <th> + </th>
        </tr>
        </thead>
        <tbody>

        {% for item in cart %}
            {% with product=item.product %}

                <tr>
                    <td><a href="{% url 'products:product_detail' product.id %}">{{ product.name }}</a></td>
                    <td>${{ product.price }}</td>

                    <td>
                        <a href="{% url 'cart:remove_from_cart' product.id %}"><button class="btn btn-primary btn-sm">Удалить</button></a>
                    </td>
                    <td>{{ item.quantity }}</td>

                    <td>
                        <a href="{% url 'cart:delete_item' product.id %}"><button class="btn btn-primary btn-sm">-</button></a>
                    </td>
                    <td>
                        <a href="{% url 'cart:add_to_cart' product.id %}"> <button class="btn btn-primary btn-sm">+</button></a>
                    </td>
                </tr>

            {% endwith %}
        {% endfor %}

        <tr class="total">
            <td>Итого</td>

            <td class="num">${{ price }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{% url "products:product_list" %}"><button class="btn btn-primary btn-lg">Каталог товаров</button></a>
    <a href="{% url "orders:create_order" %}"><button class="btn btn-primary btn-lg">Оформть заказ</button></a>
</div>
{% endblock content%}
</body>
</html>