onlinestore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from products.urls import urlpatterns as product_urls
from basket.urls import urlpatterns as cart_patterns
from orders.urls import urlpatterns as order_patterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls',namespace='products')),
    path('cart/',include('basket.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('users/',include('users.urls',namespace='users'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from products.views import product_detail, product_list

app_name = 'products'
urlpatterns = [
    path('', product_list, name='product_list'),
    path('products/<int:pk>/', product_detail, name='product_detail')

]

users/urls.py
from django.urls import path

from users.views import home, register, login_user,logout_user

app_name = 'users'
urlpatterns = [
    path('',home,name='home'),
    path('login/',login_user,name='login'),
    path('logout/',logout_user,name='logout'),
    path('registration/',register,name = 'register')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.contrib.auth import get_user_model
User = get_user_model()


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form-control form-control-lg',
            'placeholder': 'example@mail.ru',
            'autocomplete': 'email'
        })
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Придумайте имя пользователя',
                'autocomplete': 'username'
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password1'].widget.attrs.update({
            'class': 'form-control form-control-lg',
            'placeholder': 'Придумайте пароль',
            'autocomplete': 'new-password'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control form-control-lg',
            'placeholder': 'Повторите пароль',
            'autocomplete': 'new-password'
        })

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):
    username = forms.CharField(label='Введите имя',required=False,
        widget=forms.TextInput(attrs={
            'class': 'form-control form-control-lg',
            'placeholder': 'Имя пользователя',
            'autocomplete': 'username'
        })
    )

    password = forms.CharField(label='Введите пароль',required=False,
        widget=forms.PasswordInput(attrs={
            'class': 'form-control form-control-lg',
            'placeholder':'Пароль'
        })
    )

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, authenticate, logout

from users.forms import RegistrationForm, LoginForm


# Create your views here.

def register(request):
    """Регистрация пользователя"""
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('users:home')
    else:
        form = RegistrationForm()
    return render(request, 'users/register.html', {'form': form})


def login_user(request):
    """Аутентификация пользователя"""
    form = LoginForm(request.POST)
    if request.method=='POST':
        if form.is_valid():
            data = form.cleaned_data
            username = data['username']
            password = data['password']
            user = authenticate(request,username=username,password=password)
            if user is not None:
                login(request,user)
                return redirect('users:home')


    return render(request,'users/login.html',{'form':form})

def logout_user(request):
    """Выход пользователя из профиля"""
    logout(request)
    return render(request,'users/logout.html')
def home(request):
    """Профиль пользователя"""
    return render(request,'users/home.html')

templates/users/home.html
{% extends "products/base.html" %}}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>

{% block content %}
    <h1> Hello, {{ user.username }}</h1><br>
    <a href="{% url "products:product_list" %}"><button class="btn btn-primary btn-lg btn-block">Каталог товаров </button></a>
    <br>
    <a href="{% url "users:logout" %}"><button class="btn btn-primary btn-lg btn-block">Выйти</button></a>
{% endblock content %}
</body>
</html>

templates/users/login.html
{% extends "products/base.html" %}
{% block content %}
{% if error_message %}
    <p>{{ error_message }}</p>
  {% endif %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-lg btn-block">Log in</button>
</form>
  <a href="{% url 'users:register' %}"><button class="btn btn-primary btn-lg btn-block" style="margin-top:20px;">Register</button></a>
{% endblock %}

templates/users/logout.html
{% extends "products/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
{% block content %}
<h2>Logout</h2>
  <p>You have been logged out.</p>
{% endblock content%}

</body>
</html>

templates/users/register.html
{% extends "products/base.html"%}
<body>
{% block content %}
<h2>Register</h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Register</button>
</form>
{% endblock %}
</body>
</html>